services:
  - type: worker
    name: quiz-bot
    runtime: python
    rootDir: quiz_bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
